secretario/urls.py
from django.conf.urls import url

from . import views

app_name="secretario"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^404/$', views.error404, name='404'),
    #urls relacionada con grupos
	url(r'^grupos/registrar/$', views.grupos.Vista_registrar, name='registrarGrupo'),
    url(r'^registrar/grupos/$', views.grupos.registrar, name='grupos_registrar'),
    url(r'^consultar/grupos/$', views.grupos.vistaConsultar, name='conGrupo'),
    url(r'^(?P<idGrupo>[0-9]+)/grupoPublicador/$', views.grupos.conGrupoofPubs, name='conGrupoofPubs'),
    url(r'^(?P<idGrupo>[0-9]+)/datos_grupo/$', views.grupos.consultar, name='datGrupo'),
    url(r'^modGrup/$', views.grupos.modificar, name='modGrup'),
    url(r'^validarGrupo/$', views.grupos.grupoExist, name='validarGrupo'),
    url(r'^grupo/modificar/(?P<id>[0-9]+)$', views.grupos.vistaModificar, name='editGrupo'),
    url(r'^deleteG/$', views.grupos.eliminar, name='deleteG'),
    #url relacionadas con publicadores
    url(r'^regPubli/$', views.publicador.vistaRegistrar, name='regPubli'),
    url(r'^publicreg/$', views.publicador.registrar, name='publicReg'),
    url(r'^conPub/$', views.publicador.consultarNameGroup, name='conPub'),
    url(r'^cambiarpub/$', views.publicador.cambiarPub, name='cambiarPub'),
    url(r'^consultar/Publicadores/$', views.publicador.consultarTodos, name='conPubs'),
    url(r'^(?P<idpub>[0-9]+)/Publicador/$', views.publicador.consultar, name='traerPub'),
    url(r'^modPub/$', views.publicador.modificar, name='modPub'),
	url(r'^Publicador/verTarjeta$', views.publicador.verTarjetaPub, name='verTarjetaPub'),
    url(r'^conPubG/$', views.publicador.conPubG, name='conPubG'),
    #urls relacionadas con informes
	url(r'^regInf/$', views.informe.registrar, name='regInf'),
	url(r'^(?P<vista>[1-2]+)/(?P<idPub>[0-9]+)/Tarjeta/(?P<y>[0-9]+)/$', views.informe.tarjeta, name='tarjeta'),
    url(r'^modInf/$', views.informe.modificar, name='modInf'),
    #urls relacionadas con estadisticas
    url(r'^estadisticas/$', views.estadisticas.verEstadisticas, name='estadisticas'),
    url(r'^estadisticas/global', views.estadisticas.estGlobal, name='estGlobal'),
    url(r'^estadisticas/Precurs', views.estadisticas.infPrec, name='infPrec'),
    url(r'^estadisticas/Publicador', views.estadisticas.estPub, name='estPub'),
    url(r'^estadisticas/informeGeneral', views.estadisticas.obtenerInf, name='infG'),
    url(r'^PrecursInf', views.estadisticas.conInfPrec, name='conInfPrec'),
    url(r'^pubEst', views.estadisticas.conEstPub, name='conEstPub'),
    #urls relacionadas con psdfs
    url(r'^pdf/tarjeta/publicador', views.pdfs.vistaPdfPub, name='vistaPdfPub'),
    url(r'^pdfTarPub', views.pdfs.datosPdfPub, name='datosPdfPub'),
    #urls relacionadas con precursores
    url(r'^Precursores/nombrar/$', views.precursor.vistaNombrar, name='vistaNombrar'),
    url(r'^consultar/Precursor/$', views.precursor.conPrec, name='conPrec'),
    url(r'^Precursores/horas/$', views.precursor.editPrecur, name='editPrecur'),
    url(r'^nombrar/$', views.precursor.nombrar, name='NombrarPrecur'),
    url(r'^conPrecs/$', views.precursor.conPrecs, name='conPrecs'),
    url(r'^conYear/$', views.precursor.yearServicio, name='yearServicio'),
    url(r'^historia/precursor/(?P<year>[a-zA-Z0-9]+)/$', views.precursor.historiaPrec, name='historiaPrec'),
    url(r'^darBaja/$', views.precursor.darBaja, name='darBaja'),
    #urls relacionadas con usuarios
    url(r'^registrar/usuario/$', views.usuario.vistaRegistro, name='usuReg'),
    url(r'^regusu/$', views.usuario.registrar, name='Regusu'),
    #urls relacionadas con privilegios
    url(r'^privilegio/modificar$', views.privilegios.modificar, name='privMod'),
    url(r'^privilegio/consultar$', views.privilegios.consultar, name='privCon'),
    url(r'^privilegio/nombrar$', views.privilegios.Vistanombrar, name='privnombrar'),
    url(r'^privilegio/consultarnombrados$', views.privilegios.consultarNombrados, name='privconsnombrados'),
    url(r'^privnombrar$', views.privilegios.nombrar, name='nombrarPriv'),
    url(r'^privilegio/baja$', views.privilegios.baja, name='privBaja'),
    #urls relacionadas con sesion de usuarios
    url(r'^login$', views.sesion.ingreso, name='login'),
    url(r'^autenticar$', views.sesion.autenticar, name='autenticar'),
    url(r'^cerrarsesion$', views.sesion.cerrar, name='cerrar'),
]

siscong/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from secretario import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('secretario.urls')),
]

secretario/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from .forms import *
from django.core.urlresolvers import reverse
from secretario.models import *
from django.views import generic
import json
import datetime
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth.models import User

def index(request):
     return render(request, 'layout.html', {'url':0})

def registrarGrupo(request):
     form = CrearGrupo()
     return render(request, 'regGrupo.html', {'form': form, 'url':1})

def validarVacio(elements, numerosKeys=[], fechaKeys=[]):
     elemento=[]
     vacio=True
     for i in elements.keys():
          if i in numerosKeys:
               try:
                    int(elements[i])
               except(ValueError):
                    vacio=False
                    elemento.append(i)
          elif i in fechaKeys:
               try:
                    datetime.date(int(elements[i][0:4]), int(elements[i][5:7]), int(elements[i][8:]))
               except(ValueError):
                    vacio=False
                    elemento.append(i)
          else:
               if elements[i].strip()=="":
                    vacio=False
                    elemento.append(i)
     return [vacio, elemento]

def grupos_registrar(request):
     msg={}
     validar=validarVacio(request.POST)
     if validar[0]:
          _encargado=request.POST['encargado'].upper()
          _auxiliar=request.POST['auxiliar'].upper()
          _encargado=_encargado.strip()
          _auxiliar=_auxiliar.strip()
          try:
               verificar = GruposPred.objects.get(encargado=_encargado)
          except(KeyError, GruposPred.DoesNotExist):
               grupo=GruposPred(encargado=_encargado, auxiliar=_auxiliar)
               grupo.save()
               msg={'msg':"Grupo Registrado con exito", 'on':1}
          else:
               msg = {'msg': "Este encargado se encuentra en otro grupo"}
     else:
          msg=msgVacio(validar[1])
     return  HttpResponse(json.dumps(msg))

def msgVacio(vacios):
     msg={}
     if len(vacios)>0:
          msg={'msg':"Por favor no intente hacer trampa"}
     return msg

def conGrupo(request):
     try:
          request.session['idgrupo']
     except KeyError:
          cGrupo = traerGrupo()
          on = 0
     else:
          fkgrupo = request.session['idgrupo']
          if fkgrupo == "":
               cGrupo = traerGrupo()
               on = 0
          else:
               cGrupo = traerGrupo(initial={'Encargado': fkgrupo })
               request.session['idgrupo']=""
               on = 1
     return render(request, 'conGrupo.html', {'form': cGrupo, 'onPub': on, 'url':1 })

def conGrupoofPubs(request, idGrupo):
     cGrupo = traerGrupo(initial={'Encargado': idGrupo})
     return render(request, 'conGrupo.html', {'form': cGrupo, 'onPub': 1, 'url':1 })

def datGrupo(request,idGrupo):
     try:
          g = GruposPred.objects.get(pk=idGrupo)
     except(KeyError, GruposPred.DoesNotExist):
          datos={"msg":"Este grupo no esta registrado"}
     else:
          request.session['conGrupoId']=idGrupo
          p = Publicador.objects.filter(FKgrupo=g.pk)
          formDatGrupo = CrearGrupo(instance=g)
          formPub = modalPub()
          modalGrupo = traerGrupo()
          modalInfo = regInforme()
          y=str(datetime.date.today().year-1)+""+str(datetime.date.today().year)
          datos = {'form': formDatGrupo, 'publicadores': p, 'num': g.pk, 'modalPub': formPub,
                 'modalGrupo': modalGrupo, 'modalInfo': modalInfo, 'y':y, 'url':1,
                 }
     return render(request, 'datGrupo.html',datos)

def conPub(request):
     cont=0
     try:
        p=Publicador.objects.get(pk=request.POST['id'])
     except(KeyError, Publicador.DoesNotExist):
        return HttpResponse(json.dumps({'msg':'Error, Publicador no existe'}))
     else:
          p={'nombre':p.nombre, 'apellido':p.apellido,'grupo':p.FKgrupo.pk}
          datos={'pub':p}
          return HttpResponse(json.dumps(datos))

def conPubs(request):
     bajaAuto()
     promInf=[]
     try:
          request.session['msgpub']
     except KeyError:
          msg=""
     else:
          msg=request.session['msgpub']
          request.session['msgpub']=""
     c=[]
     cont=0
     pubs={}
     p=Publicador.objects.all()
     for i in p:
          inf=Informe.objects.filter(FKpub=i.pk).order_by("-year", "-mes")
          if len(inf)>0:
               status=obtenerStatus(inf[0].mes, inf[0].year)[0]
               intervalo=obtenerStatus(inf[0].mes, inf[0].year)[1]
               fecha=str(inf[0].mes)+"-"+str(inf[0].year)
               if status==0:
                    mesi=inf[0].mes
                    yeari=inf[0].year
                    mesi-=1
                    if mesi==0:
                         mesi=12
                         yeari-=1
                    informes=Informe.objects.filter(mes=mesi, year=yeari)
                    if len(informes)>0:
                         for infs in informes:
                              add=True
                              pre=PubPrecursor.objects.filter(FKpub=infs.FKpub.pk).order_by("-yearIni", "-mesIni")
                              if len(pre)>0:
                                   if pre[0].duracion==0:
                                        add=False
                                   else:
                                        fechaF=getFechaFin(pre[0].mesIni,pre[0].yearIni,pre[0].duracion)
                                        diferencia=getDiferenciaMes(fechaF[0],fechaF[1],mesi,yeari)
                                        if diferencia<0:
                                             add=False
                              if add:
                                   promInf.append(infs.horas)
                         if len(promInf)>0:
                              if prom(promInf)>inf[0].horas:
                                   status=4
          else:
               status=3
               intervalo="Este publicador nunca ha informado"
               fecha="Nulo"
          pubs[cont]={'nombre':i.nombre, 'apellido':i.apellido, 'fechaBau':i.fechaBau, 'edad':obteneredad(i), 'FKgrupo':i.FKgrupo, 'id':i.pk, 'g':i.FKgrupo.pk, 'status': status, 'intervalo': intervalo, 'fecha':fecha}
          cont=cont+1
     pubs=pubs.values()
     return render(request, 'conPubs.html',{'pub':pubs,'msg':msg, 'url':2})

def prom(nums):
     acum=0
     for i in nums:
          acum+=i
     if len(nums)>0:
          acum=acum//len(nums)
     return acum

def getDiferenciaMes(mesI, yearI, mesF, yearF):
     if yearF==yearI:
          meses=(mesF-1)-mesI
     else:
          mesYear=(yearF-yearI)*12
          mesYear=mesYear-mesI
          meses=mesYear+(mesF-1)
     return meses

def obtenerStatus(mes, year):
     hoy=datetime.date.today()
     meses=getDiferenciaMes(mes,year,hoy.month,hoy.year)
     if meses<1:
          meses=0
          status=0
     elif meses>0 and meses<7:
          status=1
     else:
          status=2
     return (status, meses)

def obteneredad(persona, tb=0):
     hoy=datetime.date.today()
     if tb==0:
          fecha=persona.fechaNa
     else:
          year=int(persona.fechaBau[0:4])
          mes=int(persona.fechaBau[5:7])
          dia=int(persona.fechaBau[8:])
          fecha=datetime.date(year,mes,dia)
     return hoy.year-fecha.year-((hoy.month, hoy.day)<(fecha.month, fecha.day))

def regPubli(request):
     formPub = regPub()
     cmbGrupo = traerGrupo()
     return render(request, 'regPubli.html', {'form': formPub, 'form2': cmbGrupo, 'url':2})

def publicReg(request):
     hoy=datetime.date.today()
     nums=['Encargado']
     vFechas=['fechaNa']
     validar=validarVacio(request.POST, nums, vFechas)
     if validar[0]:
          datosP=trimUpper(request.POST, ['email', 'fechaBau'])
          _nombre=datosP['nombre']
          _apellido=datosP['apellido']
          _telefono=datosP['telefono']
          _direccion =datosP['direccion']
          _email=datosP['email']
          _fechaBau=datosP['fechaBau']
          _fechaNa=datosP['fechaNa']
          _grupo=datosP['Encargado']
          edad=hoy.year-int(_fechaNa[0:4])-((hoy.month, hoy.day)<(int(_fechaNa[5:7]), (int(_fechaNa[8:]))))
          if edad>3:
               try:
                    pub=Publicador.objects.get(nombre=_nombre, apellido=_apellido, fechaNa=_fechaNa)
               except(KeyError, Publicador.DoesNotExist):
                    try:
                         g=GruposPred.objects.get(pk=_grupo)
                    except(KeyError, GruposPred.DoesNotExist):
                         msg={'msg':"El grupo no existe"}
                    else:
                         g.publicador_set.create(nombre=_nombre, apellido=_apellido, telefono=_telefono, direccion=_direccion,email=_email, fechaBau=_fechaBau, fechaNa=_fechaNa)
                         msg={'msg':"Publicador Registrado con exito", 'on':1}
               else:
                    msg={ 'msg': "Error! Este publicador ya esta registrado."}
          else:
               msg={'msg':"Error! Para ser registrado debe tener como minimo 4 anios"}
     else:
          msg=msgVacio(validar[1])
     return HttpResponse(json.dumps(msg))

def cambiarPub(request):
     validar=validarVacio(request.POST)
     if validar[0]:
          _p=request.POST['id']
          _g=request.POST['grupo']
          try:
               p=Publicador.objects.get(pk=_p)
          except(KeyError, Publicador.DoesNotExist):
               msg={'msg':'Publicador no existe'}
          else:
               try:
                    g=GruposPred.objects.get(pk=_g)
               except(KeyError, GruposPred.DoesNotExist):
                    msg={'msg':'Grupo no existe'}
               else:
                    if p.FKgrupo.pk!=g.pk:
                         Publicador.objects.filter(pk=_p).update(FKgrupo=g)

secretario/views/pdfs.py
#libs propios de python
import datetime
import json
#modulos de django
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
#modulos propios del proyecto
from secretario.forms import traerGrupo
from .siscong import *
from secretario.models import Publicador, Informe

@login_required(login_url='/login')
def vistaPdfPub(request):
     sesionGrupo(request)
     cGrupo = traerGrupo()
     return render(request, "Informe/pdfTarPub.html", {'form':cGrupo})

@login_required(login_url='/login')
def datosPdfPub(request):
     mK=[]
     data={}
     data['on']=1
     nums=['pub', 'year']
     validar=gestion(request.POST, nums)
     if not validar.error:
          idPub=int(request.POST['pub'])
          y=int(request.POST['year'])
          try:
               p=Publicador.objects.get(pk=idPub)
          except(KeyError, Publicador.DoesNotExist):
               data['msg']="Publicador no existe"
          else:
               data['name']=p.nombre + " " + p.apellido
               if y>0:
                    inform=Informe.objects.filter(FKpub=p.pk).order_by("year", "mes")
                    if len(inform)>0:
                         meses=arrayServicio(y)
                         keyM=meses.keys()
                         for i in keyM:
                              mK.append(i)
                         mK.sort(reverse=True)
                         for i in mK:
                              data[i]={}
                              recorrido=recorrerArrayMeses(meses[i], p.pk)
                              data[i]=recorrido[0]
                              if recorrido[1]:
                                   break
                    else:
                         data['msg']="Este publicador nunca ha informado"
               else:
                    data['msg']="La cantidad de anios de servicio no puede ser '0'"
     else:
          data=validar.mensaje
     return HttpResponse(json.dumps(data))

#metodos reutilizables

def arrayServicio(cant):
     meses={}
     yActual=datetime.date.today().year
     mActual=datetime.date.today().month
     if mActual<9:
          servicio=[yActual-1, yActual]
     else:
          servicio=[yActual, yActual+1]
          yActual+=1
     strServicio=str(servicio[0])+"-"+str(servicio[1])
     meses[strServicio]={}
     for i in range(0, cant):
          meses[strServicio]=arraymeses(yActual)
          yActual-=1
          strServicio=str(yActual-1)+"-"+str(yActual)
     return meses

secretario/templates/Publicador/regPubli.html
{% extends "layout.html" %}

{% block contenido %}

	<div id="mainPub" class="col-xs-12 col-md-10 col-lg-6 col-md-offset-1 col-lg-offset-3">
		<div class="form-panel row">

			<h1 class="visible-md visible-lg text-center titlecolor">Datos del Publicador</h1>

			<h3 class="visible-xs visible-sm text-center titlecolor">Datos del Publicador</h3>

			{% csrf_token %}
			<div class="form-group">
				<div class="col-xs-12 col-md-10 col-md-offset-1">

					{{ form }}

					<label for="fechaNa">Fecha de Nacimiento:</label>
					<div class='input-group date datepicker2 mrg-bottom'>
						<input id="fechaNA" type="text" class="form-control">
						<span class="input-group-addon">
							<span class="fa fa-calendar">
							</span>
						</span>
					</div>

					<label for="fechaBau">Fecha de Bautismo:</label>
					<div class="col-lg-12 mrg-bottom" style="padding:0px;">
						<div class='input-group dateBau datepicker2'>
							<input id="fechaBau" type="text" class="form-control">
							<span class="input-group-addon">
								<span class="fa fa-calendar">
								</span>
							</span>
						</div>
						<span class="btn btn-warning noBau">
							<span class="fa fa-calendar-times-o">
							</span>
						</span>
					</div>

					<div class="clearfix"></div>

					<div class="col-lg-12" style="padding:0px;margin-top:5px;">
						<label for="fechaBau">Sexo:</label>
						<p><input id="sexo" type="checkbox" checked></p>
					</div>
				</div>

				<div class="clearfix"></div>

				{% if on %}
					<div class="col-md-1" style="margin-top:50px;padding-left:30px;padding-top: 20px;">
						<ul class="pager" style="margin:0px;padding:0px;">
						  <li class="previous"><a href="{% url 'secretario:conPubs' %}">Volver</a></li>
						</ul>
					</div>

					<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-sm-offset-3 col-md-offset-3" style="margin-top:30px;">
						<button id="btnMod" class="btn btn-success btn-block">Modificar</button>
					</div>
				{% else %}
					<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-sm-offset-3 col-md-offset-4" style="margin-top:30px;">
						<button id="btnSave" class="btn btn-primary btn-block">Guardar</button>
					</div>
				{% endif %}
				<div class="clearfix"></div>
			</div>
		</div>    
	</div>
{% endblock %}

{% block scripts %}
	<script>
		$(document).ready(function() {
			{% if on %}
				$("#fechaNA").val("{{ fechaNa }}")
				$('#fechaBau').val("{{ fechaBau }}")

				sexo = '{{ sexo }}'
				state = $('#sexo').bootstrapSwitch('state');
				if( !state === true && sexo === 'M' ){
					$('#sexo').bootstrapSwitch('toggleState')
				}

				if( !state === false && sexo === 'F' ){
					$('#sexo').bootstrapSwitch('toggleState')
				}
			{% endif %}

			$('span.btn').click(function(){
		  		$('#fechaBau').val('No Bautizado')
		  	})

			div = $('#mainPub')
			maxwidth = $(window).width()
			if(maxwidth >= 1200 && maxwidth < 1440 ){
				div.removeClass('col-lg-6').removeClass('col-lg-offset-3')
				div.addClass('col-lg-8').addClass('col-lg-offset-2')
			} else if(maxwidth > 1440){
				div.removeClass('col-lg-8').removeClass('col-lg-offset-2')
				div.addClass('col-lg-6').addClass('col-lg-offset-3')
			}

			{% if form.fechaBau.value == "No Bautizado" %}
			  	$('#fechaBau').val('No Bautizado')
			{% endif %}

		});

		$(window).resize(function(){
			div = $('#mainPub')
			maxwidth = $(window).width()
			if(maxwidth >= 1200 && maxwidth < 1440 ){
				div.removeClass('col-lg-6').removeClass('col-lg-offset-3')
				div.addClass('col-lg-8').addClass('col-lg-offset-2')
			} else if(maxwidth > 1440){
				div.removeClass('col-lg-8').removeClass('col-lg-offset-2')
				div.addClass('col-lg-6').addClass('col-lg-offset-3')
			}
		})

		$('#btnSave').click(function(){
			datP = new Gestion()
            limpiar = function(){
                datP.Cargar()
            }

			sexo = $('#sexo').bootstrapSwitch('state');
			if(sexo === true){
				sexo = 'M'
			} else {
				sexo = 'F'
			}

			datP.getInputs('.form-group')
            inputs = datP.getDataIn()

			if ( inputs.vacio == 0 ){
				keys = new Array('nombre', 'apellido', 'telefono', 'direccion', 'email', 'fechaNa', 'fechaBau', 'sexo')
				datP.generateJson(keys, "{{ csrf_token }}", sexo)
				datP.setPost("{% url 'secretario:publicReg' %}", 'Registro de Publicadores!', limpiar)
			}
		})

		$('#btnMod').click(function(){
			redirect =  function(){
							location.href="../../consultar/Publicadores/"
						}

			sexo = $('#sexo').bootstrapSwitch('state');
			if(sexo === true){
				sexo = 'M'
			} else {
				sexo = 'F'
			}

			datMod = new Gestion()
			datMod.getInputs('.form-group')
            inputs = datMod.getDataIn()

			if (inputs.vacio==0){
				keys = new Array('nombre', 'apellido', 'telefono', 'direccion', 'email', 'fechaNa', 'fechaBau', 'sexo')
				datMod.generateJson(keys, "{{ csrf_token }}", sexo)
				datMod.setPost("{% url 'secretario:modPub' %}", 0, redirect)
			}
		})

		$("#sexo").bootstrapSwitch({
            onText: 'Hombre',
            offText: 'Mujer',
            offColor: 'default',
            state: true,
			handleWidth: 120,
        })

	</script>
{% endblock %}

secretario/templates/Publicador/verTarjetaPub.html
{% extends "layout.html" %} {% load staticfiles %} {% block contenido %}

<div class="col-md-12 col-lg-12">
	<div class="row">
		<div class="form-panel">
		    <div class="visible-md visible-lg">
				<h1 class="text-center titlecolor">Tarjeta de Actividad del Publicador</h1>
			</div>
			<div class="visible-xs visible-sm">
				<h3 class="text-center titlecolor">Tarjeta de Actividad del Publicador</h3>
			</div>

			<div class="form-horizontal style-form" style="margin-top: 30px;">
				{% csrf_token %}
				<div class="form-group">
					<div class="row">
						<div class="col-xs-12 col-lg-8 col-md-offset-0 col-lg-offset-2">

							<div class="col-lg-4">
				        		<label for="">Grupo:</label>
					        	{{ form.Encargado }}
							</div>

							<div id="cmbPubs" class="col-lg-4">
				        		<label for="">Publicador:</label>
					        	<select class="form-control">
									<option value="" >--SELECCIONE UN PUBLICADOR--</option>
								</select>
							</div>
							
							<div class="col-lg-4">
				        		<label for="">Año de Servicio:</label>
					        	<select class="form-control" disabled>
									<option value="" >--AÑO DE SERVICIO--</option>
									{% for y in years %}
									<option value="{{ y.0 }}{{ y.1 }}"> {{ y.0 }}-{{ y.1 }} </option>
									{% endfor %}
								</select>
							</div>
						</div>
					</div>

					<div class="clearfix"></div>

					<div id="datpub" class="col-lg-10 col-md-offset-1" style="display:none;margin-top:40px;margin-bottom:30px;"></div>
					
		    	</div>
			</div>		
		</div>
	</div>
</div>    

{% endblock %}

{% block scripts %}
	<script>
		//responsive
		$(window).resize(function(){
			$('span.select2-container').width( $('#cmbPubs')[0].clientWidth - 30 )
		})

		//obtener todos los selects
		combos = $('select')
		datpub = $('#datpub')

		//get all Pubs
		function loadCmbPubs(json){

			$.each(json, function(key, pub){
				if ( pub.IDpub )
					id = pub.IDpub

				if ( pub.pk )
					id = pub.pk

				combos.eq(1).append( new Option(pub.nombre+" "+pub.apellido, id) )
			})

			combos.eq(1).val("")
			combos.eq(1).trigger('change')
		}

		Pubs = {{ pubs|safe }}

		combos.eq(1).select2({
			sorter: function(results) {
						return results.sort(function(a, b) {
							if (a.value == "" || b.value == ""){
								return 0
							} else {
								return a.text == b.text ? 0 : a.text < b.text ? -1 : 1
							}
						})
					}
		})

		loadCmbPubs(Pubs)

		//nice scroll combo buscador
		combos.eq(1).on('select2:opening', function(evt){
			$("ul.select2-results__options").niceScroll({styler:"fb",cursorcolor:"#4ECDC4", cursorwidth: '6', cursorborderradius: '10px', background: '#404040', spacebarenabled:false,  cursorborder: '', zindex: '1000'})
		})

		//controladores de combos
		function loadPubs(res){
			if ( res.on == 1 ){
				$.gritter.add({
					title: "Consulta de publicadores",
					text: 'No hay publicadores en este grupo',
					image: "{% static 'img/error.png' %}",
					time: 3000,
				})
			} else{
				//cmb de publicadores
				combos.eq(1).find('option:first').siblings().detach()
				loadCmbPubs(res)

				//combo years
				combos.eq(2).attr('disabled', true).find('option:first').prop('selected', true)
				datpub.hide('blind', 1000)
			}
		}

		function llamarload(){

            idPub = combos.eq(1).val()
            year = combos.eq(2).val()

            combos.eq(2).removeAttr('disabled')

            if ( idPub != "" && year != "" ){

				cargar = new Gestion()
				cargar.ejecutarLoad("../2/"+idPub+"/Tarjeta/"+year+"", datpub)

            } else {
                if ( datpub.is(":visible") ){
                    datpub.hide('blind', 1000)
                }
                if ( idPub == "" ){
                    combos.eq(2).attr('disabled', true).find('option:first').prop('selected', true)
                }
            }
        }

		//cmb de grupos
		reorder( combos.eq(0) )//ordernar alfabeticamente

		combos.eq(0).change(function(){

            cmbG = new Gestion()
            cmbG.getInputs(".form-group", '0')
            g = cmbG.getDataIn()

			if( g.vacio == 0 ){

                keys = new Array('id', 'all')
                cmbG.generateJson(keys, '{{ csrf_token }}', 1)
                cmbG.setPost("{% url 'secretario:conPubG' %}", 0, loadPubs)

            } else {
				combos.eq(0).css('border-color', '#ccc')
				loadCmbPubs(Pubs)
				combos.eq(2).attr('disabled', true).find('option:first').prop('selected', true)
				datpub.hide('blind', 1000)
			}
        })

		//cmb de publicadores
		combos.eq(1).change(function(){
            llamarload()
		})

		//cmb de años de servicio
		combos.eq(2).change(function(){
            llamarload()
        })

	</script>
{% endblock %}