secretario/urls.py
from django.conf.urls import url

from . import views

app_name="secretario"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^404/$', views.error404, name='404'),
    #urls relacionada con grupos
	url(r'^grupos/registrar/$', views.grupos.Vista_registrar, name='registrarGrupo'),
    url(r'^registrar/grupos/$', views.grupos.registrar, name='grupos_registrar'),
    url(r'^consultar/grupos/$', views.grupos.vistaConsultar, name='conGrupo'),
    url(r'^(?P<idGrupo>[0-9]+)/grupoPublicador/$', views.grupos.conGrupoofPubs, name='conGrupoofPubs'),
    url(r'^(?P<idGrupo>[0-9]+)/datos_grupo/$', views.grupos.consultar, name='datGrupo'),
    url(r'^modGrup/$', views.grupos.modificar, name='modGrup'),
    url(r'^validarGrupo/$', views.grupos.grupoExist, name='validarGrupo'),
    url(r'^grupo/modificar/(?P<id>[0-9]+)$', views.grupos.vistaModificar, name='editGrupo'),
    url(r'^deleteG/$', views.grupos.eliminar, name='deleteG'),
    #url relacionadas con publicadores
    url(r'^regPubli/$', views.publicador.vistaRegistrar, name='regPubli'),
    url(r'^publicreg/$', views.publicador.registrar, name='publicReg'),
    url(r'^conPub/$', views.publicador.consultarNameGroup, name='conPub'),
    url(r'^cambiarpub/$', views.publicador.cambiarPub, name='cambiarPub'),
    url(r'^consultar/Publicadores/$', views.publicador.consultarTodos, name='conPubs'),
    url(r'^(?P<idpub>[0-9]+)/Publicador/$', views.publicador.consultar, name='traerPub'),
    url(r'^modPub/$', views.publicador.modificar, name='modPub'),
	url(r'^Publicador/verTarjeta$', views.publicador.verTarjetaPub, name='verTarjetaPub'),
    url(r'^conPubG/$', views.publicador.conPubG, name='conPubG'),
    #urls relacionadas con informes
	url(r'^regInf/$', views.informe.registrar, name='regInf'),
	url(r'^(?P<vista>[1-2]+)/(?P<idPub>[0-9]+)/Tarjeta/(?P<y>[0-9]+)/$', views.informe.tarjeta, name='tarjeta'),
    url(r'^modInf/$', views.informe.modificar, name='modInf'),
    #urls relacionadas con estadisticas
    url(r'^estadisticas/$', views.estadisticas.verEstadisticas, name='estadisticas'),
    url(r'^estadisticas/global', views.estadisticas.estGlobal, name='estGlobal'),
    url(r'^estadisticas/Precurs', views.estadisticas.infPrec, name='infPrec'),
    url(r'^estadisticas/Publicador', views.estadisticas.estPub, name='estPub'),
    url(r'^estadisticas/informeGeneral', views.estadisticas.obtenerInf, name='infG'),
    url(r'^PrecursInf', views.estadisticas.conInfPrec, name='conInfPrec'),
    url(r'^pubEst', views.estadisticas.conEstPub, name='conEstPub'),
    #urls relacionadas con psdfs
    url(r'^pdf/tarjeta/publicador', views.pdfs.vistaPdfPub, name='vistaPdfPub'),
    url(r'^pdfTarPub', views.pdfs.datosPdfPub, name='datosPdfPub'),
    #urls relacionadas con precursores
    url(r'^Precursores/nombrar/$', views.precursor.vistaNombrar, name='vistaNombrar'),
    url(r'^consultar/Precursor/$', views.precursor.conPrec, name='conPrec'),
    url(r'^Precursores/horas/$', views.precursor.editPrecur, name='editPrecur'),
    url(r'^nombrar/$', views.precursor.nombrar, name='NombrarPrecur'),
    url(r'^conPrecs/$', views.precursor.conPrecs, name='conPrecs'),
    url(r'^conYear/$', views.precursor.yearServicio, name='yearServicio'),
    url(r'^historia/precursor/(?P<year>[a-zA-Z0-9]+)/$', views.precursor.historiaPrec, name='historiaPrec'),
    url(r'^darBaja/$', views.precursor.darBaja, name='darBaja'),
    #urls relacionadas con usuarios
    url(r'^registrar/usuario/$', views.usuario.vistaRegistro, name='usuReg'),
    url(r'^regusu/$', views.usuario.registrar, name='Regusu'),
    #urls relacionadas con privilegios
    url(r'^privilegio/modificar$', views.privilegios.modificar, name='privMod'),
    url(r'^privilegio/consultar$', views.privilegios.consultar, name='privCon'),
    url(r'^privilegio/nombrar$', views.privilegios.Vistanombrar, name='privnombrar'),
    url(r'^privilegio/consultarnombrados$', views.privilegios.consultarNombrados, name='privconsnombrados'),
    url(r'^privnombrar$', views.privilegios.nombrar, name='nombrarPriv'),
    url(r'^privilegio/baja$', views.privilegios.baja, name='privBaja'),
    #urls relacionadas con sesion de usuarios
    url(r'^login$', views.sesion.ingreso, name='login'),
    url(r'^autenticar$', views.sesion.autenticar, name='autenticar'),
    url(r'^cerrarsesion$', views.sesion.cerrar, name='cerrar'),
]

siscong/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from secretario import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('secretario.urls')),
]

secretario/forms.py
from django import forms
from secretario.models import *

class traerGrupo(forms.Form):
	Encargado = forms.ModelChoiceField(queryset = GruposPred.objects.all().order_by("IDgrupo"),
										empty_label="--SELECCIONE UN ENCARGADO--",
										widget=forms.Select(attrs={'class': 'form-control'})
									)

class precursorados(forms.Form):
    precur = forms.ModelChoiceField(queryset = Precursor.objects.all().order_by('pk'),
                                        empty_label='Tipos de Precursorados', 
                                        widget=forms.Select(attrs={'class': 'form-control'})
                                        )

class modalPub(forms.ModelForm):
    class Meta:
        model = Publicador
        fields = ['nombre', 'apellido']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control mrg-bottom', 'disabled': 'true'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control mrg-bottom', 'disabled': 'true'}),
            }

class regPub(forms.ModelForm):
	class Meta:
		model = Publicador
		fields = ['nombre', 'apellido', 'telefono', 'direccion', 'email']
		widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control mrg-bottom'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control mrg-bottom'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control mrg-bottom'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control mrg-bottom'}),
            'email': forms.TextInput(attrs={'class': 'form-control mrg-bottom'}),
        }

class regInforme(forms.ModelForm):
    class Meta:
        model = Informe
        fields = ['minutos', 'publicaciones', 'videos', 'revisitas', 'estudios', 'observacion']
        widgets = {
            'minutos': forms.TextInput(attrs={'class': 'form-control mrg-bottom', 'type':'number', 'min':'0'}),
            'publicaciones': forms.TextInput(attrs={'class': 'form-control mrg-bottom', 'type':'number', 'min':'0'}),
            'videos': forms.TextInput(attrs={'class': 'form-control mrg-bottom', 'type':'number', 'min':'0'}),
            'revisitas': forms.TextInput(attrs={'class': 'form-control mrg-bottom', 'type':'number', 'min':'0'}),
            'estudios': forms.TextInput(attrs={'class': 'form-control mrg-bottom', 'type':'number', 'min':'0'}),
            'observacion': forms.TextInput(attrs={'class': 'form-control mrg-bottom', 'type':'text'}),
        }

secretario/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from .forms import *
from django.core.urlresolvers import reverse
from secretario.models import *
from django.views import generic
import json
import datetime
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth.models import User

def index(request):
     return render(request, 'layout.html', {'url':0})

def registrarGrupo(request):
     form = CrearGrupo()
     return render(request, 'regGrupo.html', {'form': form, 'url':1})

def validarVacio(elements, numerosKeys=[], fechaKeys=[]):
     elemento=[]
     vacio=True
     for i in elements.keys():
          if i in numerosKeys:
               try:
                    int(elements[i])
               except(ValueError):
                    vacio=False
                    elemento.append(i)
          elif i in fechaKeys:
               try:
                    datetime.date(int(elements[i][0:4]), int(elements[i][5:7]), int(elements[i][8:]))
               except(ValueError):
                    vacio=False
                    elemento.append(i)
          else:
               if elements[i].strip()=="":
                    vacio=False
                    elemento.append(i)
     return [vacio, elemento]

def grupos_registrar(request):
     msg={}
     validar=validarVacio(request.POST)
     if validar[0]:
          _encargado=request.POST['encargado'].upper()
          _auxiliar=request.POST['auxiliar'].upper()
          _encargado=_encargado.strip()
          _auxiliar=_auxiliar.strip()
          try:
               verificar = GruposPred.objects.get(encargado=_encargado)
          except(KeyError, GruposPred.DoesNotExist):
               grupo=GruposPred(encargado=_encargado, auxiliar=_auxiliar)
               grupo.save()
               msg={'msg':"Grupo Registrado con exito", 'on':1}
          else:
               msg = {'msg': "Este encargado se encuentra en otro grupo"}
     else:
          msg=msgVacio(validar[1])
     return  HttpResponse(json.dumps(msg))

def msgVacio(vacios):
     msg={}
     if len(vacios)>0:
          msg={'msg':"Por favor no intente hacer trampa"}
     return msg

def conGrupo(request):
     try:
          request.session['idgrupo']
     except KeyError:
          cGrupo = traerGrupo()
          on = 0
     else:
          fkgrupo = request.session['idgrupo']
          if fkgrupo == "":
               cGrupo = traerGrupo()
               on = 0
          else:
               cGrupo = traerGrupo(initial={'Encargado': fkgrupo })
               request.session['idgrupo']=""
               on = 1
     return render(request, 'conGrupo.html', {'form': cGrupo, 'onPub': on, 'url':1 })

def conGrupoofPubs(request, idGrupo):
     cGrupo = traerGrupo(initial={'Encargado': idGrupo})
     return render(request, 'conGrupo.html', {'form': cGrupo, 'onPub': 1, 'url':1 })

def datGrupo(request,idGrupo):
     try:
          g = GruposPred.objects.get(pk=idGrupo)
     except(KeyError, GruposPred.DoesNotExist):
          datos={"msg":"Este grupo no esta registrado"}
     else:
          request.session['conGrupoId']=idGrupo
          p = Publicador.objects.filter(FKgrupo=g.pk)
          formDatGrupo = CrearGrupo(instance=g)
          formPub = modalPub()
          modalGrupo = traerGrupo()
          modalInfo = regInforme()
          y=str(datetime.date.today().year-1)+""+str(datetime.date.today().year)
          datos = {'form': formDatGrupo, 'publicadores': p, 'num': g.pk, 'modalPub': formPub,
                 'modalGrupo': modalGrupo, 'modalInfo': modalInfo, 'y':y, 'url':1,
                 }
     return render(request, 'datGrupo.html',datos)

def conPub(request):
     cont=0
     try:
        p=Publicador.objects.get(pk=request.POST['id'])
     except(KeyError, Publicador.DoesNotExist):
        return HttpResponse(json.dumps({'msg':'Error, Publicador no existe'}))
     else:
          p={'nombre':p.nombre, 'apellido':p.apellido,'grupo':p.FKgrupo.pk}
          datos={'pub':p}
          return HttpResponse(json.dumps(datos))

def conPubs(request):
     bajaAuto()
     promInf=[]
     try:
          request.session['msgpub']
     except KeyError:
          msg=""
     else:
          msg=request.session['msgpub']
          request.session['msgpub']=""
     c=[]
     cont=0
     pubs={}
     p=Publicador.objects.all()
     for i in p:
          inf=Informe.objects.filter(FKpub=i.pk).order_by("-year", "-mes")
          if len(inf)>0:
               status=obtenerStatus(inf[0].mes, inf[0].year)[0]
               intervalo=obtenerStatus(inf[0].mes, inf[0].year)[1]
               fecha=str(inf[0].mes)+"-"+str(inf[0].year)
               if status==0:
                    mesi=inf[0].mes
                    yeari=inf[0].year
                    mesi-=1
                    if mesi==0:
                         mesi=12
                         yeari-=1
                    informes=Informe.objects.filter(mes=mesi, year=yeari)
                    if len(informes)>0:
                         for infs in informes:
                              add=True
                              pre=PubPrecursor.objects.filter(FKpub=infs.FKpub.pk).order_by("-yearIni", "-mesIni")
                              if len(pre)>0:
                                   if pre[0].duracion==0:
                                        add=False
                                   else:
                                        fechaF=getFechaFin(pre[0].mesIni,pre[0].yearIni,pre[0].duracion)
                                        diferencia=getDiferenciaMes(fechaF[0],fechaF[1],mesi,yeari)
                                        if diferencia<0:
                                             add=False
                              if add:
                                   promInf.append(infs.horas)
                         if len(promInf)>0:
                              if prom(promInf)>inf[0].horas:
                                   status=4
          else:
               status=3
               intervalo="Este publicador nunca ha informado"
               fecha="Nulo"
          pubs[cont]={'nombre':i.nombre, 'apellido':i.apellido, 'fechaBau':i.fechaBau, 'edad':obteneredad(i), 'FKgrupo':i.FKgrupo, 'id':i.pk, 'g':i.FKgrupo.pk, 'status': status, 'intervalo': intervalo, 'fecha':fecha}
          cont=cont+1
     pubs=pubs.values()
     return render(request, 'conPubs.html',{'pub':pubs,'msg':msg, 'url':2})

def prom(nums):
     acum=0
     for i in nums:
          acum+=i
     if len(nums)>0:
          acum=acum//len(nums)
     return acum

def getDiferenciaMes(mesI, yearI, mesF, yearF):
     if yearF==yearI:
          meses=(mesF-1)-mesI
     else:
          mesYear=(yearF-yearI)*12
          mesYear=mesYear-mesI
          meses=mesYear+(mesF-1)
     return meses

def obtenerStatus(mes, year):
     hoy=datetime.date.today()
     meses=getDiferenciaMes(mes,year,hoy.month,hoy.year)
     if meses<1:
          meses=0
          status=0
     elif meses>0 and meses<7:
          status=1
     else:
          status=2
     return (status, meses)

def obteneredad(persona, tb=0):
     hoy=datetime.date.today()
     if tb==0:
          fecha=persona.fechaNa
     else:
          year=int(persona.fechaBau[0:4])
          mes=int(persona.fechaBau[5:7])
          dia=int(persona.fechaBau[8:])
          fecha=datetime.date(year,mes,dia)
     return hoy.year-fecha.year-((hoy.month, hoy.day)<(fecha.month, fecha.day))

def regPubli(request):
     formPub = regPub()
     cmbGrupo = traerGrupo()
     return render(request, 'regPubli.html', {'form': formPub, 'form2': cmbGrupo, 'url':2})

def publicReg(request):
     hoy=datetime.date.today()
     nums=['Encargado']
     vFechas=['fechaNa']
     validar=validarVacio(request.POST, nums, vFechas)
     if validar[0]:
          datosP=trimUpper(request.POST, ['email', 'fechaBau'])
          _nombre=datosP['nombre']
          _apellido=datosP['apellido']
          _telefono=datosP['telefono']
          _direccion =datosP['direccion']
          _email=datosP['email']
          _fechaBau=datosP['fechaBau']
          _fechaNa=datosP['fechaNa']
          _grupo=datosP['Encargado']
          edad=hoy.year-int(_fechaNa[0:4])-((hoy.month, hoy.day)<(int(_fechaNa[5:7]), (int(_fechaNa[8:]))))
          if edad>3:
               try:
                    pub=Publicador.objects.get(nombre=_nombre, apellido=_apellido, fechaNa=_fechaNa)
               except(KeyError, Publicador.DoesNotExist):
                    try:
                         g=GruposPred.objects.get(pk=_grupo)
                    except(KeyError, GruposPred.DoesNotExist):
                         msg={'msg':"El grupo no existe"}
                    else:
                         g.publicador_set.create(nombre=_nombre, apellido=_apellido, telefono=_telefono, direccion=_direccion,email=_email, fechaBau=_fechaBau, fechaNa=_fechaNa)
                         msg={'msg':"Publicador Registrado con exito", 'on':1}
               else:
                    msg={ 'msg': "Error! Este publicador ya esta registrado."}
          else:
               msg={'msg':"Error! Para ser registrado debe tener como minimo 4 anios"}
     else:
          msg=msgVacio(validar[1])
     return HttpResponse(json.dumps(msg))

def cambiarPub(request):
     validar=validarVacio(request.POST)
     if validar[0]:
          _p=request.POST['id']
          _g=request.POST['grupo']
          try:
               p=Publicador.objects.get(pk=_p)
          except(KeyError, Publicador.DoesNotExist):
               msg={'msg':'Publicador no existe'}
          else:
               try:
                    g=GruposPred.objects.get(pk=_g)
               except(KeyError, GruposPred.DoesNotExist):
                    msg={'msg':'Grupo no existe'}
               else:
                    if p.FKgrupo.pk!=g.pk:
                         Publicador.objects.filter(pk=_p).update(FKgrupo=g)

secretario/templates/Grupo/conGrupo.html
{% extends "layout.html" %}

{% load staticfiles %}

{% block contenido %}
	<div class="col-xs-12">
		<div class="row">
			<div class="form-panel">
				<h3 class="text-center titlecolor">Seleccione un Grupo de Predicación</h3>

				{% csrf_token %}
				<div class="form-group" style="margin-top:28px">

					<div class="col-xs-10 col-sm-10 col-md-6 col-lg-4 col-md-offset-3 col-lg-offset-4">
						{{ form.Encargado }}
					</div>

					<div class="btnconXS col-xs-2 col-sm-2 col-md-1">
						<button id="btnCon" class="btn btn-primary btn-block fa fa-search" style="height:34px;"></button>
					</div>

					<div class="clearfix"></div>

					<div id="datpub" class="col-lg-12" style="display:none;margin-top: 20px;"></div>
					
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

{% block scripts %}
	<script>

		$("#btnCon").click(function(){
			encargado = $("#id_Encargado").val()
			datpub = $("#datpub")

            if( encargado ){
				$.post("{% url 'secretario:validarGrupo' %}", { 'id': encargado, csrfmiddlewaretoken: '{{ csrf_token }}' })
				.success(function(res){

					res = JSON.parse(res)

					if( res.on == 0 ){

						url = "../../"+encargado+"/datos_grupo/"
						obj = new Gestion()
						obj.ejecutarLoad(url, datpub)

					} else {
						window.location = "{% url 'secretario:404' %}"
					}
				})
            } else {
                $.gritter.add({
                    title: 'Consultar Grupos!',
                    text: 'Por favor Seleccione un Grupo',
                    image: "{% static 'img/error.png' %}",
                    time: 3000,
                });
            }
		})

		{% if onPub == 1 %}
			$("#btnCon").click()
		{% endif %}
		
	</script>
{% endblock %}

secretario/templates/Grupo/datGrupo.html
{% load staticfiles %}

<div class="row">

	<h3 class="text-center titlecolor">Informacion del Grupo</h3>

	{% csrf_token %}

	<div id="responsables" class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1">
		<div class="col-md-9">
			<span class="text-center sp-title"><strong>Encargado:</strong>
				<span class="sp-content"> {{ enc }} </span>
			</span>

			<span class="text-center sp-title" style="margin-left:30px;"><strong>Auxiliar:</strong>
				<span class="sp-content"> {{ aux }} </span>
			</span>
		</div>
		<div class="col-md-3" style="padding-right:0px;">
			<button id="edit" class="btn btn-block btn-success">Editar Grupo</button>
		</div>
	</div>

	<div class="clearfix"></div>

	<div id="pubs" class="col-xs-12 col-md-10 col-lg-10 col-md-offset-1">
		<div class="content-panel">

			<h3 class="text-center tableTitle hidden-xs">Publicadores del Grupo # {{ num }}</h3>
			<h4 class="text-center tableTitle visible-xs">Publicadores del Grupo # {{ num }}</h4>

			<section id="no-more-tables">
				<table id="grupo" class="table table-striped table-condensed cf table-Font">
					<thead class="cf">
						<tr>
							<th class="tGrupoClm1">Nombre y Apellido</th>
							<th class="tGrupoClm2">Direccion</th>
							<th class="tGrupoClm3">Telefono</th>
							<th class="tGrupoClm4">E-mail</th>
							<th class="tGrupoClm5">Estado</th>
							<th class="tGrupoClm6">Informar</th>
						</tr>
					</thead>
					<tbody>
					{% for pub in pubs %}
						<tr>
							<td class="tGrupoClm1" data-title="Nombre:">
								<a href="{% url 'secretario:tarjeta' 1 pub.id y %}">{{ pub.nombre }} {{ pub.apellido }} </a>
							</td>

							<td class="tGrupoClm2" data-title="Direccion:">
								{{ pub.direccion }}
							</td>

							<td class="tGrupoClm3" data-title="Telefono:">
								{{ pub.telefono }}
							</td>

							<td class="tGrupoClm4" data-title="E-mail:">
								{{ pub.email }}
							</td>

							<td class="tGrupoClm5" data-title="Estado">
								<div class="tGrupoStatus" style = "background-color:
									{% if pub.status == 0 %}
										#09B20F
									{% elif pub.status == 1 %}
										#FFAD33
									{% elif pub.status == 2 %}
										#B30000
									{% elif pub.status == 3 %}
										#009999
									{% else %}
										#B6B6B6
									{% endif %};"></div>
							</td>

							<td class="tGrupoClm6" id="{{ pub.id }}">
								<button class="btn btn-info fa fa-plus" data-toggle="modal" data-target="#informe"></button>
							</td>
						</tr>
					{% endfor %}
					</tbody>
				</table>
			</section>
		</div>
	</div>
</div>

{% include 'inc/modalInforme.html' %}

<script>

	var id
	var colStatus

	$(document).ready(function() {
		$('.datepicker').datetimepicker({
            format: 'MM-YYYY',
            widgetPositioning:  {
              horizontal: 'right',
              vertical: 'auto',
            },
            maxDate:'now'
        })

		maxwidth = $(window).width()
	})

	$(window).resize(function(){
		maxwidth = $(window).width()
	})

	$('#regInf').html('Registrar')
	$('.modal-title').html('Registrar Informe')
	$('#regInf').addClass('btn-primary')

	$("td > button:nth-child(1)").click(function(){
		colStatus = ""
		id = 0
		id = this.parentNode.id
		informe = new Gestion()
		informe.getInputs('#informe')
		informe.Cargar()
		colStatus = $(this).parent().siblings(':eq(4)').children()
	})

	$("#regInf").click(function(){
		close = function(res){
			$('#informe').modal('hide')
			datInf.Cargar()

			if ( res.status || res.status === 0 ){
				var status = res.status
				var color = ""
				
				if (status == 0){
					color = '#09B20F'
				} else if (status == 1){
					color = '#FFAD33'
				} else if (status == 2){
					color = '#B30000'
				} else {
					color = '#B6B6B6'
				}

				$(colStatus).css('background-color', color)
			}
		}

		hrs = $("input[type='number']:eq(2)", ".modal-body")
		if( hrs.val() > 0 ){

			obs =  $(":text:eq(0)", ".modal-body")
			if ( obs.val().trim() == "" ){
				obs.val("n/t")
			}

			HC = $("input[type='number']:eq(5)", ".modal-body")
			if ( HC.val().trim() == "" ){
				HC.val(0)
			}

			datInf = new Gestion()
			datInf.getInputs('#informe')
			input = datInf.getDataIn()

			if ( input.vacio == 0 ){
				keys = new Array('publicaciones', 'videos', 'horas', 'revisitas', 'estudios', 'obs','fecha','horasCons', 'publicador')
				datInf.generateJson(keys, '{{ csrf_token }}', id)
				datInf.setPost("{% url 'secretario:regInf' %}", 'Regitro de informe!', close)
			} else {
				showMsg('Error al Registrar Informe!','Hay Algunos Campos Vacios o con valores invalidos', "{% static 'img/error.png' %}")
			}
		} else {
			showMsg('Error al Registrar Informe!','No Puede Registrar Informes Vacios', "{% static 'img/error.png' %}")
			hrs.css('border-color', '#d90000')
		}
	})

	$("#edit").click(function(){
		window.location = "{% url 'secretario:editGrupo' num %}"
	})
</script>