secretario/urls.py
from django.conf.urls import url

from . import views

app_name="secretario"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^404/$', views.error404, name='404'),
    #urls relacionada con grupos
	url(r'^grupos/registrar/$', views.grupos.Vista_registrar, name='registrarGrupo'),
    url(r'^registrar/grupos/$', views.grupos.registrar, name='grupos_registrar'),
    url(r'^consultar/grupos/$', views.grupos.vistaConsultar, name='conGrupo'),
    url(r'^(?P<idGrupo>[0-9]+)/grupoPublicador/$', views.grupos.conGrupoofPubs, name='conGrupoofPubs'),
    url(r'^(?P<idGrupo>[0-9]+)/datos_grupo/$', views.grupos.consultar, name='datGrupo'),
    url(r'^modGrup/$', views.grupos.modificar, name='modGrup'),
    url(r'^validarGrupo/$', views.grupos.grupoExist, name='validarGrupo'),
    url(r'^grupo/modificar/(?P<id>[0-9]+)$', views.grupos.vistaModificar, name='editGrupo'),
    url(r'^deleteG/$', views.grupos.eliminar, name='deleteG'),
    #url relacionadas con publicadores
    url(r'^regPubli/$', views.publicador.vistaRegistrar, name='regPubli'),
    url(r'^publicreg/$', views.publicador.registrar, name='publicReg'),
    url(r'^conPub/$', views.publicador.consultarNameGroup, name='conPub'),
    url(r'^cambiarpub/$', views.publicador.cambiarPub, name='cambiarPub'),
    url(r'^consultar/Publicadores/$', views.publicador.consultarTodos, name='conPubs'),
    url(r'^(?P<idpub>[0-9]+)/Publicador/$', views.publicador.consultar, name='traerPub'),
    url(r'^modPub/$', views.publicador.modificar, name='modPub'),
	url(r'^Publicador/verTarjeta$', views.publicador.verTarjetaPub, name='verTarjetaPub'),
    url(r'^conPubG/$', views.publicador.conPubG, name='conPubG'),
    #urls relacionadas con informes
	url(r'^regInf/$', views.informe.registrar, name='regInf'),
	url(r'^(?P<vista>[1-2]+)/(?P<idPub>[0-9]+)/Tarjeta/(?P<y>[0-9]+)/$', views.informe.tarjeta, name='tarjeta'),
    url(r'^modInf/$', views.informe.modificar, name='modInf'),
    #urls relacionadas con estadisticas
    url(r'^estadisticas/$', views.estadisticas.verEstadisticas, name='estadisticas'),
    url(r'^estadisticas/global', views.estadisticas.estGlobal, name='estGlobal'),
    url(r'^estadisticas/Precurs', views.estadisticas.infPrec, name='infPrec'),
    url(r'^estadisticas/Publicador', views.estadisticas.estPub, name='estPub'),
    url(r'^estadisticas/informeGeneral', views.estadisticas.obtenerInf, name='infG'),
    url(r'^PrecursInf', views.estadisticas.conInfPrec, name='conInfPrec'),
    url(r'^pubEst', views.estadisticas.conEstPub, name='conEstPub'),
    #urls relacionadas con psdfs
    url(r'^pdf/tarjeta/publicador', views.pdfs.vistaPdfPub, name='vistaPdfPub'),
    url(r'^pdfTarPub', views.pdfs.datosPdfPub, name='datosPdfPub'),
    #urls relacionadas con precursores
    url(r'^Precursores/nombrar/$', views.precursor.vistaNombrar, name='vistaNombrar'),
    url(r'^consultar/Precursor/$', views.precursor.conPrec, name='conPrec'),
    url(r'^Precursores/horas/$', views.precursor.editPrecur, name='editPrecur'),
    url(r'^nombrar/$', views.precursor.nombrar, name='NombrarPrecur'),
    url(r'^conPrecs/$', views.precursor.conPrecs, name='conPrecs'),
    url(r'^conYear/$', views.precursor.yearServicio, name='yearServicio'),
    url(r'^historia/precursor/(?P<year>[a-zA-Z0-9]+)/$', views.precursor.historiaPrec, name='historiaPrec'),
    url(r'^darBaja/$', views.precursor.darBaja, name='darBaja'),
    #urls relacionadas con usuarios
    url(r'^registrar/usuario/$', views.usuario.vistaRegistro, name='usuReg'),
    url(r'^regusu/$', views.usuario.registrar, name='Regusu'),
    #urls relacionadas con privilegios
    url(r'^privilegio/modificar$', views.privilegios.modificar, name='privMod'),
    url(r'^privilegio/consultar$', views.privilegios.consultar, name='privCon'),
    url(r'^privilegio/nombrar$', views.privilegios.Vistanombrar, name='privnombrar'),
    url(r'^privilegio/consultarnombrados$', views.privilegios.consultarNombrados, name='privconsnombrados'),
    url(r'^privnombrar$', views.privilegios.nombrar, name='nombrarPriv'),
    url(r'^privilegio/baja$', views.privilegios.baja, name='privBaja'),
    #urls relacionadas con sesion de usuarios
    url(r'^login$', views.sesion.ingreso, name='login'),
    url(r'^autenticar$', views.sesion.autenticar, name='autenticar'),
    url(r'^cerrarsesion$', views.sesion.cerrar, name='cerrar'),
]

siscong/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from secretario import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('secretario.urls')),
]

secretario/forms.py
from django import forms
from secretario.models import *

class traerGrupo(forms.Form):
	Encargado = forms.ModelChoiceField(queryset = GruposPred.objects.all().order_by("IDgrupo"),
										empty_label="--SELECCIONE UN ENCARGADO--",
										widget=forms.Select(attrs={'class': 'form-control'})
									)

class precursorados(forms.Form):
    precur = forms.ModelChoiceField(queryset = Precursor.objects.all().order_by('pk'),
                                        empty_label='Tipos de Precursorados', 
                                        widget=forms.Select(attrs={'class': 'form-control'})
                                        )

class modalPub(forms.ModelForm):
    class Meta:
        model = Publicador
        fields = ['nombre', 'apellido']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control mrg-bottom', 'disabled': 'true'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control mrg-bottom', 'disabled': 'true'}),
            }

class regPub(forms.ModelForm):
	class Meta:
		model = Publicador
		fields = ['nombre', 'apellido', 'telefono', 'direccion', 'email']
		widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control mrg-bottom'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control mrg-bottom'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control mrg-bottom'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control mrg-bottom'}),
            'email': forms.TextInput(attrs={'class': 'form-control mrg-bottom'}),
        }

class regInforme(forms.ModelForm):
    class Meta:
        model = Informe
        fields = ['minutos', 'publicaciones', 'videos', 'revisitas', 'estudios', 'observacion']
        widgets = {
            'minutos': forms.TextInput(attrs={'class': 'form-control mrg-bottom', 'type':'number', 'min':'0'}),
            'publicaciones': forms.TextInput(attrs={'class': 'form-control mrg-bottom', 'type':'number', 'min':'0'}),
            'videos': forms.TextInput(attrs={'class': 'form-control mrg-bottom', 'type':'number', 'min':'0'}),
            'revisitas': forms.TextInput(attrs={'class': 'form-control mrg-bottom', 'type':'number', 'min':'0'}),
            'estudios': forms.TextInput(attrs={'class': 'form-control mrg-bottom', 'type':'number', 'min':'0'}),
            'observacion': forms.TextInput(attrs={'class': 'form-control mrg-bottom', 'type':'text'}),
        }

secretario/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from .forms import *
from django.core.urlresolvers import reverse
from secretario.models import *
from django.views import generic
import json
import datetime
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth.models import User

def index(request):
     return render(request, 'layout.html', {'url':0})

def registrarGrupo(request):
     form = CrearGrupo()
     return render(request, 'regGrupo.html', {'form': form, 'url':1})

def validarVacio(elements, numerosKeys=[], fechaKeys=[]):
     elemento=[]
     vacio=True
     for i in elements.keys():
          if i in numerosKeys:
               try:
                    int(elements[i])
               except(ValueError):
                    vacio=False
                    elemento.append(i)
          elif i in fechaKeys:
               try:
                    datetime.date(int(elements[i][0:4]), int(elements[i][5:7]), int(elements[i][8:]))
               except(ValueError):
                    vacio=False
                    elemento.append(i)
          else:
               if elements[i].strip()=="":
                    vacio=False
                    elemento.append(i)
     return [vacio, elemento]

def grupos_registrar(request):
     msg={}
     validar=validarVacio(request.POST)
     if validar[0]:
          _encargado=request.POST['encargado'].upper()
          _auxiliar=request.POST['auxiliar'].upper()
          _encargado=_encargado.strip()
          _auxiliar=_auxiliar.strip()
          try:
               verificar = GruposPred.objects.get(encargado=_encargado)
          except(KeyError, GruposPred.DoesNotExist):
               grupo=GruposPred(encargado=_encargado, auxiliar=_auxiliar)
               grupo.save()
               msg={'msg':"Grupo Registrado con exito", 'on':1}
          else:
               msg = {'msg': "Este encargado se encuentra en otro grupo"}
     else:
          msg=msgVacio(validar[1])
     return  HttpResponse(json.dumps(msg))

def msgVacio(vacios):
     msg={}
     if len(vacios)>0:
          msg={'msg':"Por favor no intente hacer trampa"}
     return msg

def conGrupo(request):
     try:
          request.session['idgrupo']
     except KeyError:
          cGrupo = traerGrupo()
          on = 0
     else:
          fkgrupo = request.session['idgrupo']
          if fkgrupo == "":
               cGrupo = traerGrupo()
               on = 0
          else:
               cGrupo = traerGrupo(initial={'Encargado': fkgrupo })
               request.session['idgrupo']=""
               on = 1
     return render(request, 'conGrupo.html', {'form': cGrupo, 'onPub': on, 'url':1 })

def conGrupoofPubs(request, idGrupo):
     cGrupo = traerGrupo(initial={'Encargado': idGrupo})
     return render(request, 'conGrupo.html', {'form': cGrupo, 'onPub': 1, 'url':1 })

def datGrupo(request,idGrupo):
     try:
          g = GruposPred.objects.get(pk=idGrupo)
     except(KeyError, GruposPred.DoesNotExist):
          datos={"msg":"Este grupo no esta registrado"}
     else:
          request.session['conGrupoId']=idGrupo
          p = Publicador.objects.filter(FKgrupo=g.pk)
          formDatGrupo = CrearGrupo(instance=g)
          formPub = modalPub()
          modalGrupo = traerGrupo()
          modalInfo = regInforme()
          y=str(datetime.date.today().year-1)+""+str(datetime.date.today().year)
          datos = {'form': formDatGrupo, 'publicadores': p, 'num': g.pk, 'modalPub': formPub,
                 'modalGrupo': modalGrupo, 'modalInfo': modalInfo, 'y':y, 'url':1,
                 }
     return render(request, 'datGrupo.html',datos)

def conPub(request):
     cont=0
     try:
        p=Publicador.objects.get(pk=request.POST['id'])
     except(KeyError, Publicador.DoesNotExist):
        return HttpResponse(json.dumps({'msg':'Error, Publicador no existe'}))
     else:
          p={'nombre':p.nombre, 'apellido':p.apellido,'grupo':p.FKgrupo.pk}
          datos={'pub':p}
          return HttpResponse(json.dumps(datos))

def conPubs(request):
     bajaAuto()
     promInf=[]
     try:
          request.session['msgpub']
     except KeyError:
          msg=""
     else:
          msg=request.session['msgpub']
          request.session['msgpub']=""
     c=[]
     cont=0
     pubs={}
     p=Publicador.objects.all()
     for i in p:
          inf=Informe.objects.filter(FKpub=i.pk).order_by("-year", "-mes")
          if len(inf)>0:
               status=obtenerStatus(inf[0].mes, inf[0].year)[0]
               intervalo=obtenerStatus(inf[0].mes, inf[0].year)[1]
               fecha=str(inf[0].mes)+"-"+str(inf[0].year)
               if status==0:
                    mesi=inf[0].mes
                    yeari=inf[0].year
                    mesi-=1
                    if mesi==0:
                         mesi=12
                         yeari-=1
                    informes=Informe.objects.filter(mes=mesi, year=yeari)
                    if len(informes)>0:
                         for infs in informes:
                              add=True
                              pre=PubPrecursor.objects.filter(FKpub=infs.FKpub.pk).order_by("-yearIni", "-mesIni")
                              if len(pre)>0:
                                   if pre[0].duracion==0:
                                        add=False
                                   else:
                                        fechaF=getFechaFin(pre[0].mesIni,pre[0].yearIni,pre[0].duracion)
                                        diferencia=getDiferenciaMes(fechaF[0],fechaF[1],mesi,yeari)
                                        if diferencia<0:
                                             add=False
                              if add:
                                   promInf.append(infs.horas)
                         if len(promInf)>0:
                              if prom(promInf)>inf[0].horas:
                                   status=4
          else:
               status=3
               intervalo="Este publicador nunca ha informado"
               fecha="Nulo"
          pubs[cont]={'nombre':i.nombre, 'apellido':i.apellido, 'fechaBau':i.fechaBau, 'edad':obteneredad(i), 'FKgrupo':i.FKgrupo, 'id':i.pk, 'g':i.FKgrupo.pk, 'status': status, 'intervalo': intervalo, 'fecha':fecha}
          cont=cont+1
     pubs=pubs.values()
     return render(request, 'conPubs.html',{'pub':pubs,'msg':msg, 'url':2})

def prom(nums):
     acum=0
     for i in nums:
          acum+=i
     if len(nums)>0:
          acum=acum//len(nums)
     return acum

def getDiferenciaMes(mesI, yearI, mesF, yearF):
     if yearF==yearI:
          meses=(mesF-1)-mesI
     else:
          mesYear=(yearF-yearI)*12
          mesYear=mesYear-mesI
          meses=mesYear+(mesF-1)
     return meses

def obtenerStatus(mes, year):
     hoy=datetime.date.today()
     meses=getDiferenciaMes(mes,year,hoy.month,hoy.year)
     if meses<1:
          meses=0
          status=0
     elif meses>0 and meses<7:
          status=1
     else:
          status=2
     return (status, meses)

def obteneredad(persona, tb=0):
     hoy=datetime.date.today()
     if tb==0:
          fecha=persona.fechaNa
     else:
          year=int(persona.fechaBau[0:4])
          mes=int(persona.fechaBau[5:7])
          dia=int(persona.fechaBau[8:])
          fecha=datetime.date(year,mes,dia)
     return hoy.year-fecha.year-((hoy.month, hoy.day)<(fecha.month, fecha.day))

def regPubli(request):
     formPub = regPub()
     cmbGrupo = traerGrupo()
     return render(request, 'regPubli.html', {'form': formPub, 'form2': cmbGrupo, 'url':2})

def publicReg(request):
     hoy=datetime.date.today()
     nums=['Encargado']
     vFechas=['fechaNa']
     validar=validarVacio(request.POST, nums, vFechas)
     if validar[0]:
          datosP=trimUpper(request.POST, ['email', 'fechaBau'])
          _nombre=datosP['nombre']
          _apellido=datosP['apellido']
          _telefono=datosP['telefono']
          _direccion =datosP['direccion']
          _email=datosP['email']
          _fechaBau=datosP['fechaBau']
          _fechaNa=datosP['fechaNa']
          _grupo=datosP['Encargado']
          edad=hoy.year-int(_fechaNa[0:4])-((hoy.month, hoy.day)<(int(_fechaNa[5:7]), (int(_fechaNa[8:]))))
          if edad>3:
               try:
                    pub=Publicador.objects.get(nombre=_nombre, apellido=_apellido, fechaNa=_fechaNa)
               except(KeyError, Publicador.DoesNotExist):
                    try:
                         g=GruposPred.objects.get(pk=_grupo)
                    except(KeyError, GruposPred.DoesNotExist):
                         msg={'msg':"El grupo no existe"}
                    else:
                         g.publicador_set.create(nombre=_nombre, apellido=_apellido, telefono=_telefono, direccion=_direccion,email=_email, fechaBau=_fechaBau, fechaNa=_fechaNa)
                         msg={'msg':"Publicador Registrado con exito", 'on':1}
               else:
                    msg={ 'msg': "Error! Este publicador ya esta registrado."}
          else:
               msg={'msg':"Error! Para ser registrado debe tener como minimo 4 anios"}
     else:
          msg=msgVacio(validar[1])
     return HttpResponse(json.dumps(msg))

def cambiarPub(request):
     validar=validarVacio(request.POST)
     if validar[0]:
          _p=request.POST['id']
          _g=request.POST['grupo']
          try:
               p=Publicador.objects.get(pk=_p)
          except(KeyError, Publicador.DoesNotExist):
               msg={'msg':'Publicador no existe'}
          else:
               try:
                    g=GruposPred.objects.get(pk=_g)
               except(KeyError, GruposPred.DoesNotExist):
                    msg={'msg':'Grupo no existe'}
               else:
                    if p.FKgrupo.pk!=g.pk:
                         Publicador.objects.filter(pk=_p).update(FKgrupo=g)

secretario/templates/conTarjetaGrupoPub.html
{% extends "layout.html" %}

{% block contenido %}

<div class="col-lg-12">
	<div class="row">
		<div class="form-panel">
		    <div class="visible-md visible-lg">
				<h1 class="text-center titlecolor"><i class="fa fa-angle-right"></i>Datos de Actividad del Publicador</h1>
			</div>
			<div class="visible-xs visible-sm">
				<h3 class="text-center"><i class="fa fa-angle-right"></i>Datos de Actividad del Publicador</h3>
			</div>

	<div class="form-horizontal style-form">
		{% csrf_token %}
		<div class="form-group">
			<div class="col-lg-10 col-md-offset-1" style="margin-top: 30px;">
				{% include 'tarjetaPub.html' %}
			</div>

			<div class="clearfix"></div>

			<div class="col-xs-1" style="margin-top:50px;margin-left:30px;">
				<ul class="pager" style="margin:0px;padding:0px;">
				  <li class="previous"><a href="{% url 'secretario:conGrupo' %}">Volver</a></li>
				</ul>
			</div>
		</div>
	</div>		

		</div>
	</div>
</div>    

{% endblock %}

secretario/templates/layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Otniel Acevedo">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">

    <title>Inicio</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

    <!--iconos-->
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/font-awesome.css' %}" />

    <!-- styles libraries -->
    <link href="{% static 'js/datepicker/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" />
    <link href="{% static 'js/datatable/jquery.dataTables.min.css' %}" rel="stylesheet" />
    <link href="{% static 'js/datatable/select.dataTables.min.css' %}" rel="stylesheet" />
    <link href="{% static 'js/jqueryUI/jquery-ui.min.css' %}" rel="stylesheet" />
    <link href="{% static 'js/bootstrap-switch/bootstrap-switch.css' %}" rel="stylesheet" />
    <link href="{% static 'js/gritter/css/jquery.gritter.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'js/icheck/flat/green.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'js/smartWizard/wizard_vertical_custom.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'js/select2/select2.min.css' %}" rel="stylesheet" type="text/css" />

	<!--Plantilla styles -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/table-responsive.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style-responsive.css' %}" />

    <!-- styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/siscong.css' %}" />

</head>

<body>

    <section id="container">

        <!--header start-->
        <header class="header black-bg">
            <div class="sidebar-toggle-box">
                <div class="fa fa-bars tooltips visible-xs visible-sm" data-placement="right" data-original-title="Toggle Navigation"></div>
            </div>
            <!--logo start-->
            <a href="/" class="logo"><b>SISCONG - Sistema Administrativo para las congregaciones</b></a>
            <!--logo end-->
            <div class="top-menu">
                <ul class="nav pull-right top-menu">
                    <li><a class="logout" href="{% url 'secretario:cerrar' %}">SALIR</a></li>
                </ul>
            </div>
        </header>
        <!--header end-->

        <!--MAIN SIDEBAR MENU-->
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion">
                    <li class="mt">
                        <a class="{% if url == 0 %} active {% endif %}" href="{% url 'secretario:index' %}">
                            <i class="fa fa-home"></i>
                            <span>Inicio</span>
                        </a>
                    </li>

                    <li class="sub-menu">
                        <a href="" class="{% if url == 1 %} active {% endif %}">
                            <i class="fa fa-users"></i>
                            <span>Grupos</span>
                        </a>
                        <ul class="sub">
                            <li><a href="{% url 'secretario:registrarGrupo' %}">Crear</a></li>
                            <li><a href="{% url 'secretario:conGrupo' %}">Consultar</a></li>
                        </ul>
                    </li>

                    <li class="sub-menu">
                        <a href="" class="{% if url == 2 %} active {% endif %}">
                            <i class="fa fa-male"></i>
                            <span>Publicador</span>
                        </a>
                        <ul class="sub">
                            <li><a href="{% url 'secretario:regPubli' %}">Registrar</a></li>
                            <li><a href="{% url 'secretario:conPubs' %}">Consultar</a></li>
                            <li><a href="{% url 'secretario:verTarjetaPub' %}">Ver Tarjeta</a></li>
                        </ul>
                    </li>

                	<li class="sub-menu">
                        <a href="">
                            <i class="fa fa-sitemap"></i>
                            <span>Privilegios</span>
                        </a>
                        <ul class="sub">
                            <li><a href="{% url 'secretario:privCon' %}">Consultar</a></li>
                            <li><a href="{% url 'secretario:privnombrar' %}">Nombrar</a></li>
                            <li><a href="{% url 'secretario:privconsnombrados' %}">Consultar Nombrados</a></li>
                        </ul>
                    </li>

                    <li class="sub-menu">
                        <a href="" class="{% if url == 3 %} active {% endif %}">
                            <i class="fa fa-clock-o"></i>
                            <span>Precursores</span>
                        </a>
                        <ul class="sub">
                            <li><a href="{% url 'secretario:vistaNombrar' %}">Nombrar</a></li>
                            <li><a href="{% url 'secretario:conPrec' %}">Consultar</a></li>
                            <!-- <li><a href="{% url 'secretario:editPrecur' %}">Modificar Precursorado</a></li> -->
                        </ul>
                    </li>

                    <li class="sub-menu">
                        <a href="">
                            <i class="fa fa-file-text-o"></i>
                            <span>Informes</span>
                        </a>
                        <ul class="sub">
                            <li><a href="{% url 'secretario:estadisticas' %}">Estadisticas</a></li>
                            <li><a href="{% url 'secretario:vistaPdfPub' %}">Tarjeta del publicador</a></li>
                        </ul>
                    </li>

                    <li class="mt">
                        <a href="{% url 'secretario:usuReg' %}">
                            <i class="fa fa-user"></i>
                            <span>Usuarios</span>
                        </a>
                    </li>
                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->

        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
                <div class="row">
                    {% block contenido %}
                    <div class="welcome-message">
                        <div class="welcome-message__content">
                            <h1>Bienvenido a SISCONG</h1>
                            <p>Ingrese en alguno de los menús y comience a gestionar su congregación</p>
                        </div>
                    </div>
                    {% endblock %}
                </div>
            </section>
        </section>
        <!--main content end-->

    </section>

    <!-- librerias obligatorias -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jqueryUI/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/gritter/js/jquery.gritter.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/siscong.js' %}"></script>

    <!-- librerias para el funcionamiento del layaout -->
    <script src="{% static 'js/jquery.dcjqaccordion.2.7.js' %}" type="text/javascript" class="include"></script>
    <script src="{% static 'js/jquery.ui.touch-punch.min.js' %}"></script>
    <script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/common-scripts.js' %}"></script>

    <!-- librerias dataTable -->
    <script src="{% static 'js/datatable/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/datatable/dataTables.select.min.js' %}"></script>
    <script src="{% static 'js/datatable/filtros.js' %}"></script>

    <!-- librerias dataTimePicker -->
    <script src="{% static 'js/datepicker/moment.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/datepicker/es.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/datepicker/bootstrap-datetimepicker.min.js' %}" type="text/javascript"></script>

    <!-- libreria del switche boostrap -->
    <script src="{% static 'js/bootstrap-switch/bootstrap-switch.js' %}" type="text/javascript"></script>

    <!-- libreria del icheck -->
    <script src="{% static 'js/icheck/icheck.js' %}" type="text/javascript"></script>

    <!-- libreria para graficos -->
    <script src="{% static 'js/Chart.min.js' %}"></script>

	<!-- librerias para el PDF -->
	<script src="{% static 'js/pdfmake/pdfmake.min.js' %}"></script>
	<script src="{% static 'js/pdfmake/vfs_fonts.js' %}"></script>

    <!-- librerias para el jquery smartWizard -->
    <script src="{% static 'js/smartWizard/jquery.smartWizard.js' %}"></script>

    <!-- librerias para el combo buscador -->
    <script src="{% static 'js/select2/select2.min.js' %}"></script>

    {% block scripts %} {% endblock %}

</body>

</html>